steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cloudrun-backend:latest', '.' ]
logsBucket: gs://jjzeng-cloudbuild-logs
images:
- 'gcr.io/$PROJECT_ID/cloudrun-backend'
