apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: cloudrun-backend # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
        - image: gcr.io/jjzeng-knative-dev/cloudrun-backend
          env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "from cloudrun backend"
